config/routes.rb
SystemStatus::Application.routes.draw do
  resources :outage_types

  resources :status_reports

end

app/models/outage_type.rb
class OutageType < ActiveRecord::Base
	has_many :status_reports
end

app/models/status_report.rb
class StatusReport < ActiveRecord::Base
	belongs_to :outage_type
	
	validates :name, :presence => true
	validates :outage_type_id, :presence => true,
				   :numericality => { :only_integer => true }
	validates :start_time, :presence => true,
			       :numericality => { :only_integer => true, :less_than => 2400 }
	validates :affected_groups, :presence => true
	validates :affected_services, :presence => true
	validates :description, :presence => true
	validates :created_by, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/outage_types_controller.rb
class OutageTypesController < ApplicationController
  # GET /outage_types
  # GET /outage_types.json
  def index
    @outage_types = OutageType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outage_types }
    end
  end

  # GET /outage_types/1
  # GET /outage_types/1.json
  def show
    @outage_type = OutageType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outage_type }
    end
  end

  # GET /outage_types/new
  # GET /outage_types/new.json
  def new
    @outage_type = OutageType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outage_type }
    end
  end

  # GET /outage_types/1/edit
  def edit
    @outage_type = OutageType.find(params[:id])
  end

  # POST /outage_types
  # POST /outage_types.json
  def create
    @outage_type = OutageType.new(params[:outage_type])

    respond_to do |format|
      if @outage_type.save
        format.html { redirect_to @outage_type, notice: 'Outage type was successfully created.' }
        format.json { render json: @outage_type, status: :created, location: @outage_type }
      else
        format.html { render action: "new" }
        format.json { render json: @outage_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outage_types/1
  # PUT /outage_types/1.json
  def update
    @outage_type = OutageType.find(params[:id])

    respond_to do |format|
      if @outage_type.update_attributes(params[:outage_type])
        format.html { redirect_to @outage_type, notice: 'Outage type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outage_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outage_types/1
  # DELETE /outage_types/1.json
  def destroy
    @outage_type = OutageType.find(params[:id])
    @outage_type.destroy

    respond_to do |format|
      format.html { redirect_to outage_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/status_reports_controller.rb
class StatusReportsController < ApplicationController
  # GET /status_reports
  # GET /status_reports.json
  def index
    @status_reports = StatusReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @status_reports }
    end
  end

  # GET /status_reports/1
  # GET /status_reports/1.json
  def show
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status_report }
    end
  end

  # GET /status_reports/new
  # GET /status_reports/new.json
  def new
    @status_report = StatusReport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status_report }
    end
  end

  # GET /status_reports/1/edit
  def edit
    @status_report = StatusReport.find(params[:id])
  end

  # POST /status_reports
  # POST /status_reports.json
  def create
    @status_report = StatusReport.new(params[:status_report])

    respond_to do |format|
      if @status_report.save
        format.html { redirect_to @status_report, notice: 'Status report was successfully created.' }
        format.json { render json: @status_report, status: :created, location: @status_report }
      else
        format.html { render action: "new" }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /status_reports/1
  # PUT /status_reports/1.json
  def update
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      if @status_report.update_attributes(params[:status_report])
        format.html { redirect_to @status_report, notice: 'Status report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_reports/1
  # DELETE /status_reports/1.json
  def destroy
    @status_report = StatusReport.find(params[:id])
    @status_report.destroy

    respond_to do |format|
      format.html { redirect_to status_reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outage_types_helper.rb
module OutageTypesHelper
end

app/helpers/status_reports_helper.rb
module StatusReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SystemStatus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/outage_types/_form.html.erb
<%= form_for(@outage_type) do |f| %>
  <% if @outage_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outage_type.errors.count, "error") %> prohibited this outage_type from being saved:</h2>

      <ul>
      <% @outage_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outage_types/edit.html.erb
<h1>Editing outage_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @outage_type %> |
<%= link_to 'Back', outage_types_path %>

app/views/outage_types/index.html.erb
<h1>Listing outage_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Description</th>
    <th>Active</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outage_types.each do |outage_type| %>
  <tr>
    <td><%= outage_type.name %></td>
    <td><%= outage_type.code %></td>
    <td><%= outage_type.description %></td>
    <td><%= outage_type.active %></td>
    <td><%= outage_type.created_by %></td>
    <td><%= link_to 'Show', outage_type %></td>
    <td><%= link_to 'Edit', edit_outage_type_path(outage_type) %></td>
    <td><%= link_to 'Destroy', outage_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outage type', new_outage_type_path %>

app/views/outage_types/new.html.erb
<h1>New outage_type</h1>

<%= render 'form' %>

<%= link_to 'Back', outage_types_path %>

app/views/outage_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @outage_type.name %>
</p>

<p>
  <b>Code:</b>
  <%= @outage_type.code %>
</p>

<p>
  <b>Description:</b>
  <%= @outage_type.description %>
</p>

<p>
  <b>Active:</b>
  <%= @outage_type.active %>
</p>

<p>
  <b>Created by:</b>
  <%= @outage_type.created_by %>
</p>


<%= link_to 'Edit', edit_outage_type_path(@outage_type) %> |
<%= link_to 'Back', outage_types_path %>

app/views/status_reports/_form.html.erb
<%= form_for(@status_report) do |f| %>
  <% if @status_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_report.errors.count, "error") %> prohibited this status_report from being saved:</h2>

      <ul>
      <% @status_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :outage_type_id %><br />
    <%= f.number_field :outage_type_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.number_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.number_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :affected_groups %><br />
    <%= f.text_field :affected_groups %>
  </div>
  <div class="field">
    <%= f.label :affected_services %><br />
    <%= f.text_field :affected_services %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :scheduled %><br />
    <%= f.check_box :scheduled %>
  </div>
  <div class="field">
    <%= f.label :resolved %><br />
    <%= f.check_box :resolved %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_reports/edit.html.erb
<h1>Editing status_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_report %> |
<%= link_to 'Back', status_reports_path %>

app/views/status_reports/index.html.erb
<h1>Listing status_reports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Outage type</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Affected groups</th>
    <th>Affected services</th>
    <th>Description</th>
    <th>Scheduled</th>
    <th>Resolved</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @status_reports.each do |status_report| %>
  <tr>
    <td><%= status_report.name %></td>
    <td><%= status_report.outage_type_id %></td>
    <td><%= status_report.start_time %></td>
    <td><%= status_report.end_time %></td>
    <td><%= status_report.affected_groups %></td>
    <td><%= status_report.affected_services %></td>
    <td><%= status_report.description %></td>
    <td><%= status_report.scheduled %></td>
    <td><%= status_report.resolved %></td>
    <td><%= status_report.created_by %></td>
    <td><%= status_report.created_at %></td>
    <td><%= status_report.updated_at %></td>
    <td><%= link_to 'Show', status_report %></td>
    <td><%= link_to 'Edit', edit_status_report_path(status_report) %></td>
    <td><%= link_to 'Destroy', status_report, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status report', new_status_report_path %>

app/views/status_reports/new.html.erb
<h1>New status_report</h1>

<%= render 'form' %>

<%= link_to 'Back', status_reports_path %>

app/views/status_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status_report.name %>
</p>

<p>
  <b>Outage type:</b>
  <%= @status_report.outage_type_id %>
</p>

<p>
  <b>Start time:</b>
  <%= @status_report.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @status_report.end_time %>
</p>

<p>
  <b>Affected groups:</b>
  <%= @status_report.affected_groups %>
</p>

<p>
  <b>Affected services:</b>
  <%= @status_report.affected_services %>
</p>

<p>
  <b>Description:</b>
  <%= @status_report.description %>
</p>

<p>
  <b>Scheduled:</b>
  <%= @status_report.scheduled %>
</p>

<p>
  <b>Resolved:</b>
  <%= @status_report.resolved %>
</p>

<p>
  <b>Created by:</b>
  <%= @status_report.created_by %>
</p>

<p>
  <b>Created at:</b>
  <%= @status_report.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @status_report.updated_at %>
</p>


<%= link_to 'Edit', edit_status_report_path(@status_report) %> |
<%= link_to 'Back', status_reports_path %>